# /etc/greetd/config.toml

[terminal]
# Który terminal wirtualny użyć (zazwyczaj tty1)
vt = 1

[default_session]
# Komenda uruchamiająca greeter
command = "tuigreet --time --remember --remember-session --asterisks --greeting 'Welcome to Sway' --cmd sway"
user = "greeter"
